### ISSUE TITLE
3.接口返回身份证已存在 前端无提示

### ISSUE THREAD

**Issue by zhangzimo123** [hollykunge/LarkServer#154]
操作步骤：
1.登录系统
2.点击 系统管理-用户管理-新增用户
3.姓名输入 te1 身份证号输入110111111111111111 密级输入：非密 在职状态选择在职 点击保存
4.再次创建用户：姓名输入 te2 身份证号输入110111111111111111 密级输入：非密  点击保存

预期结果：保存失败 提示身份证已存在
实际结果：点击保存无反应

**Comment by hollykunge** [comment]
范娇

**Comment by zhangzimo123** [comment]
此问题已在1.0.1版本修改
