### ISSUE TITLE
websocker发送消息到研讨后端服务器的消息json字符串缺少接收人（群）的姓名

### ISSUE THREAD

**Issue by zhuqingze** [hollykunge/LarkServer#372]

**Comment by jihainan** [comment]
描述一下你的场景，我测试是有的

**Comment by zhuqingze** [comment]
我前端代码可能比较旧了，等我更新再确认下，当时debug后端看有两个发送人姓名。


 
---原始邮件---
发件人: "jihainan"<notifications@github.com>
发送时间: 2019年7月25日(星期四) 晚上7:28
收件人: "hollykunge/LarkServer"<LarkServer@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"zhuqingze"<785531296@qq.com>;
主题: Re: [hollykunge/LarkServer] websocker发送消息到研讨后端服务器的消息json字符串缺少接收人（群）的姓名 (#372)



描述一下你的场景，我测试是有的

**Comment by jihainan** [comment]
消息体的结构设计完全依赖于前端逻辑，修改结构会导致前端逻辑出现问题，目前暂时无法修改。

**Comment by zhuqingze** [comment]
好的 了解


 
---原始邮件---
发件人: "jihainan"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 中午11:23
收件人: "hollykunge/LarkServer"<LarkServer@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"zhuqingze"<785531296@qq.com>;
主题: Re: [hollykunge/LarkServer] websocker发送消息到研讨后端服务器的消息json字符串缺少接收人（群）的姓名 (#372)



消息体的结构设计完全依赖于前端逻辑，修改结构会导致前端逻辑出现问题，目前暂时无法修改。
